Feature/fetching data
moyad37/Frontend_task pull request #10
Opened 2024-04-23 07:26 UTC by moyad37

Fetching data using fetch(), 
I added buttons in flex layout for data.name and a hidden <ul> for the other data.

fixes #7

2024-04-23 09:39 UTC, krali-johnny requested changes

2024-04-23 09:39 UTC, krali-johnny commented on my-react-app/src/components/GetData/DataItem.tsx
> +      <h1 className="font-bold">{data.title}</h1>
sehr gut gemacht .. um die daten noch besser anzuzeigen verwendest du bitte ein modal welches aufgeht wenn man auf einem button drückt und die entsprechenden daten anzeigt die der film enthält 

dafür kannst du einfach mal googlen nach packages welches du installieren und verwenden kannst um modals schnell und einfach anzuwenden ..

eines was ich auf die schnelle gefunden hätt wär 

https://www.npmjs.com/package/react-modal

kannst aber gerne ein package oder component library deiner wahl nehmen

2024-04-23 09:39 UTC, krali-johnny commented on my-react-app/src/components/GetData/GetData.tsx
> +    fetch("https://freetestapi.com/api/v1/movies")
sehr gut gemacht! gefällt mir... 

 jetzt versuchst du noch das ganze mit hilfe von axios oder noch besser mit react query ( tanstack) zu implementieren.. ich weis das kann schon kompliziert sein aber solche dinge sind für einen FE dev essentiell zu verstehen .. bei unklarheiten einfach fragen :)

2024-04-23 09:39 UTC, krali-johnny commented on my-react-app/src/components/GetData/GetData.tsx
> +type Data = {
mitarbeitsplus... mit type is einfach nur genial :)

2024-04-23 09:39 UTC, krali-johnny commented on my-react-app/tailwind.config.js
> +  content: ["./src/App.tsx", "./src/components/Buttons/Buttons.tsx", "./src/components/Buttons/ColorfulButton.tsx", "./src/components/GetData/GetData.tsx", "./src/components/GetData/DataItem.tsx"],
laut tailwind docu erspart die folgender replace das ständige händische adden von weiteren componenets 

`content: ['./src/**/*.{html,js,jsx,ts,tsx}'],`

2024-04-24 17:41 UTC, moyad37 commented
ich habe die data mit axios und tanstack gefetcht + modal component mit ein einfachen design.

ich habe aber noch immer errors im konsole die ich nicht ganz verstanden habe.

2024-04-25 06:32 UTC, krali-johnny commented
![Screenshot 2024-04-25 at 08 30 39](https://github.com/moyad37/Frontend_task/assets/74065197/108ce667-9dd1-4af2-972d-7b88da283b4b)


die erste meldung kommt von Fontawesome.. da hast irgendwas nicht richtig gmacht mit dem aufsetzten/installieren von fontawesome einfach mal das getting started von fontawesome durchlesen und nochmal durch machen 

wenns nochmal kommst schaun wirs uns gemeinsam an 


das zweite kannst mal ignorieren 

die dritte kommt von react modal.. kann es sein dass du dieses package falsch verwendest ?

2024-04-25 06:50 UTC, krali-johnny requested changes

2024-04-25 06:50 UTC, krali-johnny commented on my-react-app/src/components/GetData/DataItem.tsx
> +      <Modal
versuche das modal in eine extra componentente + file auszulagern und die benötigten daten über die props rein zu geben

2024-04-25 06:50 UTC, krali-johnny commented on my-react-app/src/components/GetData/DataItem.tsx
> +            {"Year : "}
geschwungene klammern sind unnötig... cl Year : auch in einem span packen dann is es fair aufgeteilt

2024-04-25 06:50 UTC, krali-johnny commented on my-react-app/src/components/GetData/DataItem.tsx
> +            {" "}
weg mit der zeile

2024-04-25 06:50 UTC, krali-johnny commented on my-react-app/src/components/GetData/DataItem.tsx
> +              {"Link to Website"}
auch hier geschwungen klammer und hochkommern kannst/solltest weglassen

2024-04-25 06:50 UTC, krali-johnny commented on my-react-app/src/components/GetData/GetData.tsx
> +      const response = await axios.get("https://freetestapi.com/api/v1/movies");
sehr gut gemacht jetzt verwenden wir react query noch um die daten invalide zu schalten sobald der user ein modal zu macht 

react query speichert die geladenen daten ja in einem art cache zwischen, damit die app nicht immer die daten neu laden muss, wenn man weis dass sich an den daten sowieso nichts geändert hat. jetzt wollen wir aber dem package mitteilen dass sich eventuell an den daten was verändert hat. das können wir indem wir der query sagen dass die daten invalide sind, react query holt sich die aktualisierten dann von ganz alleine.. 

einfach mal googlen und die docu durschschauen.. sollte nicht so schwer sein umzusetzen aber ganz wichtiges feature von tanstack

2024-04-25 13:46 UTC, moyad37 commented
Ich muss noch die cache ding machen mit der query :)

ich habe den Modal Component in einem eignen file ausgelagert, es war ein bisschen nicht so einfach die data zu den modal component weiter zu geben, aber jetzt funktioniert.

ich werde heute Nacht noch die letzte review versuchen zu machen

2024-04-30 10:14 UTC, krali-johnny requested changes
wie besprochen network tab verfolgen .. endlose api abfrage

2024-04-30 10:14 UTC, krali-johnny commented on my-react-app/src/components/Modal/ModalItemList.tsx
> +  return (
() => (<div></div>)

2024-04-30 10:14 UTC, krali-johnny commented on my-react-app/src/components/GetData/GetData.tsx
> +      queryClient.invalidateQueries(["posts"]);
fix errors in IDE 

await queryClient.invalidateQueries({queryKey: ['posts']});

2024-04-30 11:47 UTC, krali-johnny approved these changes
![image](https://github.com/moyad37/Frontend_task/assets/74065197/41ea821e-3564-468b-8690-f27df1de49b5)

2024-05-02 09:42 UTC, merged