init. new code
moyad37/Frontend_task pull request #3
Opened 2024-04-15 12:10 UTC by moyad37

2024-04-15 12:21 UTC, krali-johnny requested changes
bei fragen einfach direkt in die kommentare hier oder sonst anrufen wennst dich gar ned auskennst :)

2024-04-15 12:21 UTC, krali-johnny commented on my-react-app/src/App.tsx
> +function AddButton(props: { class: string; })
add button ist hier eine eigen component und sollte somit in eine eigenes file ausgelagert werden

2024-04-15 12:21 UTC, krali-johnny commented on my-react-app/src/App.tsx
> +function AddButton(props: { class: string; })
wenn du dir den sitelife code anschaust dann fällt dir auf das wir coponents immer mit einer anonymen funktion aufbauen.. also immer () => {}

bitte dieses pattern einhalten

2024-04-15 12:21 UTC, krali-johnny commented on my-react-app/src/App.tsx
> +function Buttons()
Auch hier eine eigen cmponente welche ausgelagert gehört

2024-04-15 12:21 UTC, krali-johnny commented on my-react-app/src/App.tsx
> +      <div>
den standard create react app code kannst raus löschen

2024-04-15 12:21 UTC, krali-johnny commented on my-react-app/src/App.tsx
> +    <button onClick={ () => handleColor(props.class)} className={props.class} id="myButton"> ClassName : {props.class.substring(3)} </button>
niemals ein css style mit hifle von ids setzen dazu bitte immer css klassen anlegen

da wir aber das plugin tailwind css installiert haben solltest du in deisem projekt nichts mit css lösen sondern immer nur tailwind klassen anwenden 

bitte dazu mal kurz ein youtube video anschauen was tailwind ist und wie man es benützt 

dann brauchst du auch kein css mehr schreiben in diesem projekt

2024-04-15 12:21 UTC, krali-johnny commented on my-react-app/src/App.tsx
> +function AddButton(props: { class: string; })
für den type der componente auch sitelife code anschauen wir haben da immer einen extrigen type angelegt,, dass bitte hier auch machen

2024-04-16 11:14 UTC, moyad37 commented
Ich habe folgendes gemacht: 
die addButton component wurde jetzt innerhalb eine .map() angeruft,
type component,
alle css style in den ClassName impliziert

2024-04-16 13:16 UTC, krali-johnny requested changes
schaut schon viel besser aus.. guter progress.. weiter soo

2024-04-16 13:16 UTC, krali-johnny commented on my-react-app/src/App.tsx
> +      <h1>Vite + React</h1>
zeile 15 bis 35 einfach mal raus hauen das brauchen wir nicht mehr

2024-04-16 13:16 UTC, krali-johnny commented on my-react-app/src/components/Buttons/AddButton.tsx
> +    ButtonColor:string;
props and variables bitte immer mit kleinen buchstaben starten und componenten mit großen buchstaben

2024-04-16 13:16 UTC, krali-johnny commented on my-react-app/src/components/Buttons/AddButton.tsx
> +    ButtonStyle:string;
bei deiner formatierung haut auch irgenwas ned hin.. googled bitte mal prettier und enable es für dein visual code bzw für diese projekt einfach mal tutorials über prettier anschauen und wie du dieses bei dir lokal einschalten und benutzen kannst

2024-04-16 13:16 UTC, krali-johnny commented on my-react-app/src/components/Buttons/AddButton.tsx
> +  let textColor = ButtonColor;
kannst du mir kurz erklären was du mit dieser funktion machen wolltest vl kann ich dir zeigen wie wir das lösen können ?

2024-04-16 13:16 UTC, krali-johnny commented on my-react-app/src/components/Buttons/AddButton.tsx
> +    <>
diese spitzen klammern nennt man in react fragments (einfach mal googlen für was die gut sind und für was man diese braucht und warum es die überhaupt gibt)

auf jedenfall brauchen wir sie in diesem fall nicht können diese auch hier löschen

2024-04-16 13:16 UTC, krali-johnny commented on my-react-app/src/components/Buttons/Buttons.tsx
> +    const [buttonStyle, setButtonStyle] = useState(["p-8", "m-4" ,"border-2", "rounded-lg", "hover:-translate-y-2", "duration-150"]);
für das braucht man keinen state anlegen dass kann man direkt in der AddButton componente machen

2024-04-16 13:16 UTC, krali-johnny commented on my-react-app/src/components/Buttons/Buttons.tsx
> +    const [buttonStyle, setButtonStyle] = useState(["p-8", "m-4" ,"border-2", "rounded-lg", "hover:-translate-y-2", "duration-150"]);
dafür sollten wir kurz telefonieren dass ich zeige wie ich das meine

2024-04-16 13:16 UTC, krali-johnny commented on my-react-app/src/components/Buttons/Buttons.tsx
> +            {colorsClasses.map((color, index) => (
nice .. coole idee.. weiter soo :)

2024-04-16 13:16 UTC, krali-johnny commented on my-react-app/src/components/Buttons/Buttons.tsx
> +    {/*
den comment code bitte raus hauen

2024-04-17 12:37 UTC, moyad37 commented
-- Ich habe den code nach Alex`s und deine Tipps einfacher und mehr lesbar gemacht,
-- die style class namen direkt in der AddButton componente geschrieben, 
-- und plus eine text color class name wenn der button schwarz ist soll den text weiß sein, 
-- alle unnötigen comments gelöscht
-- fragments gelöscht weil ich die in diesen Fall nicht brauche

2024-04-17 13:00 UTC, krali-johnny requested changes

2024-04-17 13:00 UTC, krali-johnny commented on my-react-app/src/components/Buttons/Buttons.tsx
> +function Buttons()
hier die anonyme function pattern verwenden () => {}

2024-04-17 13:00 UTC, krali-johnny commented on my-react-app/src/components/Buttons/AddButton.tsx
> +    buttonColor:string;
bitte unbedingt mal prettier anschauen die formatierung des codes haut ned hin

2024-04-17 13:00 UTC, krali-johnny commented on my-react-app/src/components/Buttons/AddButton.tsx
> +const AddButton = ({buttonColor}:Props) =>
benenne die componente mal um da wir hier nix adden oder so lass dir einen namen einfallen der mit action des buttons zu tun hat

2024-04-17 13:00 UTC, krali-johnny commented on my-react-app/src/components/Buttons/Buttons.tsx
> +    const colorsClasses = [
bei arrays gibt man immer einen namen der die mehrzahl im englischen ausdrückt (endet meistens mit einem s) oder die keywords array oder list am ende trägt (diese lösung aber eher vermeiden da der variablen name ziemlich lang wird)

hier spricht man von colorClasses oder colors oder classes aber nicht von colorsClasses 

da du hier zweifache mehrzahl drinnan hast und in diesem fall eher falsch wäre

2024-04-18 07:32 UTC, krali-johnny approved these changes
super gemacht weiter so :)

2024-04-18 07:33 UTC, merged